# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Astro

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
collections_config:
  data:
    path: data
    disable_add: true
    disable_add_folder: true
  pages:
    path: src/content/pages
    url: "/[slug]/"
    output: true
    icon: wysiwyg
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: note_add
    schemas:
      default:
        name: New Page
        path: schemas/page.md
        new_preview_url: "/"
    _inputs:
      content_blocks:
        empty_type: array
    filter:
      base: strict

_structures:
  features:
    values:
      - value:
          item:
          isActive:

# source: src

# data_config:
#   preferences: data/preferences.json

paths:
  static: public
  uploads: src/assets/[collection]/[relative_path]

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Australia/Perth

generator:
  metadata:
    markdown: markdown-it
    markdown-it:
      html: true
      linkify: true
