# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Astro

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
source: /

paths:
  static: public
  uploads: public/[collection]/[relative_path]

collections_config:
  data:
    name: Preferences
    path: data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  pages:
    path: src/content/pages
    url: "/[full_slug]/"
    icon: wysiwyg
    sort:
      key: order
      order: asc
    sort_options:
      - key: order
      - key: title
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: note_add
    schemas:
      default:
        name: New Page
        path: schemas/page.md
        new_preview_url: "/cc-newpage"
        hide_extra_inputs: true
        remove_extra_inputs: false
    preview:
      metadata:
        - text:
            - key: status
          icon: "circle"
    _inputs:
      title:
        type: text
      description:
        type: text
      status:
        type: select
        options:
          values:
            - online
            - hidden
            - meta
            - offline
      thumbnail:
        type: image
      order:
        type: number
        options:
          step: 1
      content_blocks:
        type: array
      categories:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          empty_type: array
        values:
          - ""
      publishDate:
        type: datetime
        instance_value: NOW
      expiryDate:
        type: datetime
      show_global_header:
        type: checkbox
      show_global_footer:
        type: checkbox

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Preferences
    collections:
      - data

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Australia/Perth

markdown:
  engine: commonmark
  options:
    linkify: true
    html: true
    xhtml: true

_inputs:
  content:
    type: markdown
    label: Content
    options:
      link: true
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      snippet: true
      horizontalrule: true
      image: false
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: src/styles/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true
  htmlcontent:
    type: html
    label: Content
    options:
      link: true
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      snippet: true
      horizontalrule: true
      image: false
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: src/styles/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true
  classes:
    label: Style
    type: array
    options:
      empty_type: array
  classes[*]:
    type: text
  indent:
    label: Indent
    type: multichoice
    options:
      allow_empty: true
      values:
        - no-indent
        - no-indent-top
        - no-indent-bottom
        - no-indent-left
        - no-indent-right
  height:
    type: range
    options:
      step: 1
      max: 100
      min: 0
  align:
    type: choice
    options:
      values:
        - top
        - center
        - bottom
  animation:
    type: choice
    options:
      allow_empty: true
      values:
        - fade
        - blur
        - slide-up
        - slide-right
        - slide-down
        - slide-left
        - grow
        - flare
  background_video:
    type: url
    comment: Use a Vimeo video as a background for this section.
  background_align:
    type: choice
    options:
      values:
        - top left
        - top
        - top right
        - left
        - center
        - right
        - bottom left
        - bottom
        - bottom right
  background_opacity:
    type: range
    options:
      step: 1
      max: 100
      min: 0
  background_fixed:
    type: checkbox
  alt:
    type: text
    comment: Alt text should describe the subject of an image as an accessability feature for screen-readers.
  background_fit:
    type: choice
    options:
      values:
        - cover
        - contain

_snippets_imports:
  mdx: true
_snippets:
  facebook:
    template: mdx_component
    inline: false
    preview:
      icon: thumb_up
      text: Facebook
    definitions:
      component_name: Facebook
  social:
    template: mdx_component
    inline: true
    preview:
      icon: share
      text: Social
    definitions:
      component_name: Social
      named_args:
        - source_key: align
          editor_key: align
          type: string
          optional: true
        - source_key: show-text
          editor_key: show-text
          type: boolean
          optional: true
    _inputs:
      align:
        type: choice
        options:
          values:
            - left
            - center
            - right
            - space-between
            - space-evenly
      show-text:
        type: checkbox
  counter:
    template: mdx_paired_component
    inline: true
    preview:
      text: Counter
      icon: plus_one
    definitions:
      component_name: Counter
      content_key: htmlcontent
  accordion:
    template: mdx_paired_component
    inline: false
    preview:
      text: Accordion
      icon: expand_more
      subtext:
        - key: title
    definitions:
      component_name: Accordion
      content_key: htmlcontent
      named_args:
        - source_key: title
          editor_key: title
          type: string
          optional: false
    _inputs:
      title:
        type: text
  player:
    template: mdx_component
    inline: false
    preview:
      icon: movie
      text: Video Player
    definitions:
      component_name: Player
      named_args:
        - source_key: src
          editor_key: src
          type: string
          optional: false
    _inputs:
      src:
        type: url
  navigation:
    template: mdx_component
    inline: false
    preview:
      icon: account_tree
      text: Navigation
    definitions:
      component_name: Navigation
      named_args:
        - source_key: filter
          editor_key: filter
          type: string
          optional: true
        - source_key: maxDepth
          editor_key: maxDepth
          type: number
          optional: true
        - source_key: parent
          editor_key: parent
          type: boolean
          optional: true
        - source_key: hide-cousins
          editor_key: hide-cousins
          type: boolean
          optional: true
    _inputs:
      filter:
        type: text
      maxDepth:
        type: number
        options:
          min: 1
          step: 1
      parent:
        type: checkbox
      hide_cousins:
        type: checkbox
  img:
    template: mdx_component
    inline: false
    preview:
      icon: image
      text: Inline Image
      image:
        - key: src
      subtext:
        - key: alt
        - key: title
      gallery:
        image:
          - key: src
    definitions:
      component_name: img
      named_args:
        - editor_key: src
          type: string
          optional: false
        - editor_key: size
          source_key: data-size
          type: string
          optional: true
          remove_empty: true
        - editor_key: align
          source_key: data-align
          type: string
          optional: true
          remove_empty: true
        - editor_key: title
          type: string
          optional: true
          remove_empty: true
        - editor_key: alt
          type: string
          optional: true
          remove_empty: true
    _inputs:
      src:
        type: image
        label: Image
      size:
        type: choice
        options:
          allow_empty: true
          values:
            - small
            - medium
            - large
      align:
        type: choice
        options:
          allow_empty: true
          values:
            - left
            - center
            - right

_structures:
  content_blocks:
    style: modal
    values: []
