# Read the CloudCannon documentation for more information on how to use this file:
# https://cloudcannon.com/documentation/articles/setting-global-configuration/?ssg=Astro

# Collections are related sets of content files, typically grouped by folder.
# Here you can define your collections, as well as any
# CloudCannon configuration specific to those collections.
source: /

paths:
  static: public
  uploads: public/[collection]/[relative_path]

collections_config:
  data:
    name: Preferences
    path: data
    disable_add: true
    disable_add_folder: true
    disable_file_actions: true
  pages:
    path: src/content/pages
    url: "/[full_slug]/"
    icon: wysiwyg
    sort:
      key: order
      order: asc
    sort_options:
      - key: order
      - key: title
    _enabled_editors:
      - visual
    add_options:
      - name: Add New Page
        schema: default
        icon: note_add
    schemas:
      default:
        name: New Page
        path: schemas/page.md
        new_preview_url: "/cc-newpage"
        hide_extra_inputs: true
        remove_extra_inputs: false
    preview:
      metadata:
        - text:
            - key: status
          icon: "circle"
    _inputs:
      title:
        type: text
      description:
        type: text
      status:
        type: select
        options:
          values:
            - online
            - hidden
            - meta
            - offline
      thumbnail:
        type: image
      order:
        type: number
        options:
          step: 1
      content_blocks:
        type: array
      categories:
        type: multiselect
        options:
          allow_create: true
          allow_empty: true
          empty_type: array
      publishDate:
        type: datetime
        instance_value: NOW
      expiryDate:
        type: datetime
      show_global_header:
        type: checkbox
      show_global_footer:
        type: checkbox

collection_groups:
  - heading: Pages
    collections:
      - pages
  - heading: Preferences
    collections:
      - data

# Timezone of your site in IANA format. This is used by date and datetime inputs
# within the CloudCannon Data Editor.
timezone: Australia/Perth

markdown:
  engine: commonmark
  options:
    linkify: true
    html: true
    xhtml: true

_inputs:
  content:
    type: markdown
    options:
      link: true
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      snippet: true
      horizontalrule: true
      image: true
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: src/styles/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true
  htmlcontent:
    type: html
    options:
      link: true
      blockquote: true
      bold: true
      format: p h1 h2 h3 h4 h5 h6 pre address div
      italic: true
      strike: true
      subscript: true
      superscript: true
      underline: true
      bulletedlist: true
      indent: true
      numberedlist: true
      outdent: true
      code: true
      embed: true
      snippet: true
      horizontalrule: true
      image: false
      table: true
      undo: true
      redo: true
      removeformat: true
      copyformatting: true
      styles: src/styles/editor.css
      left: align-left
      center: align-center
      right: align-right
      justify: align-justify
      image_size_attributes: true
  classes:
    label: Style
    type: multiselect
    options:
      allow_create: true
      values:
        - no-indent
        - no-indent-top
        - no-indent-bottom
        - no-indent-left
        - no-indent-right
  section:
    type: object
    options:
      subtype: mutable

_structures:
  section:
    values:
      - label: Section
        default: true
        value:
          height:
          color:
          content:
          background_color:
          background_image:
          background_video:
          background_align:
          background_opacity:
          background_fixed:
          classes:
        place_groups_below: true
        groups:
          - heading: Background
            inputs:
              - background_color
              - background_image
              - background_video
              - background_align
              - background_opacity
              - background_fixed

_snippets_imports:
  mdx: true
_snippets:
  facebook:
    template: mdx_component
    inline: false
    preview:
      icon: thumb_up
    definitions:
      component_name: Facebook
  social:
    template: mdx_component
    inline: true
    preview:
      icon: share
    definitions:
      component_name: Social
      named_args:
        - source_key: align
          editor_key: align
          type: string
          optional: true
        - source_key: show-text
          editor_key: show-text
          type: boolean
          optional: true
    _inputs:
      align:
        type: choice
        options:
          values:
            - left
            - center
            - right
            - space-between
            - space-evenly
      show-text:
        type: checkbox
  counter:
    template: mdx_paired_component
    inline: true
    definitions:
      component_name: Counter
      content_key: content
  accordion:
    template: mdx_paired_component
    inline: false
    definitions:
      component_name: Accordion
      content_key: htmlcontent
      named_args:
        - source_key: title
          editor_key: title
          type: string
          optional: false
    preview:
      icon: expand
      subtext:
        - key: title
    _inputs:
      title:
        type: text
  player:
    template: mdx_component
    inline: false
    preview:
      icon: movie
    definitions:
      component_name: Player
      named_args:
        - source_key: src
          editor_key: src
          type: string
          optional: false
    _inputs:
      src:
        type: url
  image:
    template: mdx_component
    inline: false
    preview:
      icon: image
      subtext:
        - key: caption
        - key: title
        - key: alt
        - key: src
      gallery:
        image:
          - key: src
    definitions:
      component_name: Image
      named_args:
        - source_key: src
          editor_key: src
          type: string
          optional: false
        - source_key: alt
          editor_key: alt
          type: string
          optional: false
        - source_key: title
          editor_key: title
          type: string
          optional: true
        - source_key: caption
          editor_key: caption
          type: string
          optional: true
        - source_key: caption
          editor_key: caption
          type: string
          optional: true
        - source_key: float
          editor_key: float
          type: string
          optional: true
        - source_key: fit
          editor_key: fit
          type: string
          optional: true
        - source_key: class
          editor_key: classes
          type: string
          optional: true
    _inputs:
      src:
        type: image
      alt:
        type: text
        comment: Descriptive fallback text for screen readers and search engines.
      title:
        type: text
        comment: Informational text shown on mouse hover.
      caption:
        type: text
        comment: Caption text beneath the image.
      float:
        type: choice
        comment: Position the image
        options:
          values:
            - Float Left
            - Center
            - Float Right
      fit:
        type: choice
        comment: Adjust how the image is sized.
        options:
          values:
            - Contain
            - Cover
      classes:
        label: Style
        type: multiselect
        options:
          allow_create: true
  navigation:
    template: mdx_component
    inline: false
    preview:
      icon: account_tree
    definitions:
      component_name: Navigation
      named_args:
        - source_key: filter
          editor_key: filter
          type: string
          optional: true
        - source_key: maxDepth
          editor_key: maxDepth
          type: number
          optional: true
        - source_key: parent
          editor_key: parent
          type: boolean
          optional: true
        - source_key: hide-cousins
          editor_key: hide-cousins
          type: boolean
          optional: true
    _inputs:
      filter:
        type: text
      maxDepth:
        type: number
        options:
          min: 1
          step: 1
      parent:
        type: checkbox
      hide_cousins:
        type: checkbox
